# Generated by Django 4.0.4 on 2022-05-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Area Code',
                'verbose_name_plural': 'Area Codes',
                'db_table': 'area_codes',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('is_avaliable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'db_table': 'phone_numbers',
            },
        ),
    ]
